### ISSUE TITLE
タスク登録画面の作成

### ISSUE THREAD

**Issue by yama-ari** [yama-ari/Split_to_Act#17]

**Comment by yama-ari** [comment]
タイムゾーンと言語の変更
```
#config/application.rb
config.time_zone = "Tokyo"
config.i18n.default_locale = :ja
```
日本語のロケールファイルをja.ymlに配置
`docker compose run web touch config/locales/ja.yml`

**Comment by yama-ari** [comment]
- [ ] ページネーションの追加
```
gem "kaminari"
```
`docker compose exec web bundle install`

- [ ] Taskコントローラの修正
```
def index
  @tasks = Task.page(params[:page])
end
```

- [ ] Task/indexにページネーション追加
```
<%= paginate @cats %>
```

`docker compose run web touch config/locales/aminari.ja.yml`
```
# 参考: https://github.com/tigrish/kaminari-i18n/blob/master/config/locales/ja.yml
ja:
  helpers:
    page_entries_info:
      more_pages:
        display_entries: "<b>%{total}</b>中の%{entry_name}を表示しています <b>%{first} - %{last}</b>"
      one_page:
        display_entries:
          one: "<b>%{count}</b>レコード表示中です %{entry_name}"
          other: "<b>%{count}</b>レコード表示中です %{entry_name}"
          zero: "レコードが見つかりませんでした %{entry_name}"
  views:
    pagination:
      first: "&laquo; 最初"
      last: "最後 &raquo;"
      next: "次 &rsaquo;"
      previous: "&lsaquo; 前"
      truncate: "&hellip;"
```

- [ ] kaminariの設定ファイル
`docker compose exec web rails generate kaminari:config`
```
config.default_per_page = 10
```

**Comment by yama-ari** [comment]
- [ ] バリデーションの設定
```
#app/models/task.rb
validates :title, presence: true, length: { minimum: 3, maximum: 20 }
  validates :memo, allow_blank: true, length: { minimum: 3, maximum: 500 }
  validates :estimated_time, allow_blank: true, numericality: true
```

**Comment by yama-ari** [comment]
メモ:scaffolldをviewからマイグレーションファイルから全部消すコマンド
'docker compose exec web rails destroy scaffold Task'

**Comment by yama-ari** [comment]
今のところ使わない機能(タイトル以外)をコメントアウトしました

**Comment by yama-ari** [comment]
■gem 'rails-i18n'を導入する

- [ ] Gemfileに、gem 'rails-i18n', '~> 7.0.0' を記述
`docker compose run web bundle install`
`docker compose restart`
`docker compose exec web bin/dev`

- [ ] config/locales/views/ja.ymlを生成する
```
#参考
ja:
  helpers:
    submit:
      create: 登録
      submit: 保存
      update: 更新
    label:
      email: メールアドレス
      password: パスワード
  user_sessions:
    new:
      title: ログイン
      login: ログイン
      to_register_page: 登録ページへ
      password_forget: パスワードをお忘れの方はこちら
  users:
    new:
      title: ユーザー登録
      to_login_page: ログインページへ
  header:
    login: ログイン
    logout: ログアウト
    board: 掲示板
    board_index: 掲示板一覧
    create_board: 掲示板作成
    bookmark_index: ブックマーク一覧
    profile: プロフィール
```

- [ ] t(' ')で囲っていく
